export const projects = [
  {
    id: 1,
    imgSrc: "../../assets/projects/leadmarvels-advert.png",
    imgAlt: "Lead Marvels Website",
    link: "https://leadmarvels.com",
    title: "Lead Marvels Website",
    description: "Laravel | Apline.js | Tailwindscss",
  },
  {
    id: 2,
    imgSrc: "/src/assets/projects/leadmarvels-newsletter.png",
    imgAlt: "MECPA Knowledge Hub",
    link: "https://mecpahub.org/",
    title: "Leadmarvels Newsletter Component",
    description: "Laravel | Apline.js | Tailwindscss",
  },
  {
    id: 3,
    imgSrc: "/src/assets/projects/mecpahub.png",
    imgAlt: "MECPA Knowledge Hub",
    link: "https://mecpahub.org/",
    title: "MECPA Knowledge Hub",
    description: "Laravel | Apline.js | Tailwindscss",
  },
  {
    id: 4,
    imgSrc: "/src/assets/projects/iacpahub.png",
    imgAlt: "IACPAHUB Resource",
    link: "https://tinyurl.com/3tt7ffay",
    title: "IACPAHUB Resource",
    description: "Laravel | Apline.js | Tailwindscss",
  },
  {
    id: 5,
    imgSrc: "/src/assets/projects/smeshowcase.png",
    imgAlt: "Dekkerbabian Website",
    link: "https://andrewamelinckx.com",
    title: "Dekkerbabian Website",
    description: "Laravel | Apline.js | Tailwindscss",
  },
  {
    id: 6,
    imgSrc: "/src/assets/projects/alloravineyards.png",
    imgAlt: "Dekkerbabian Website",
    link: "https://andrewamelinckx.com",
    title: "Dekkerbabian Website",
    description: "Laravel | Bootstrap",
  },
  {
    id: 7,
    imgSrc: "/src/assets/projects/amelinckx.png",
    imgAlt: "Andrew Amelinckx Website",
    link: "https://andrewamelinckx.com",
    title: "Andrew Amelinckx Website",
    description: "React Tailwindscss",
  },
  {
    id: 8,
    imgSrc: "/src/assets/projects/dekkerbabian.png",
    imgAlt: "Andrew Amelinckx Website",
    link: "https://andrewamelinckx.com",
    title: "Andrew Amelinckx Website",
    description: "React | Tailwindscss",
  },
  {
    id: 9,
    imgSrc: "/src/assets/projects/hinkeinrealty.png",
    imgAlt: "Andrew Amelinckx Website",
    link: "https://andrewamelinckx.com",
    title: "Andrew Amelinckx Website",
    description: "Wordpress",
  },
];
