export const projects = [
  {
    id: 1,
    imgSrc: "/projects/leadmarvels-advert.png",
    imgAlt: "Lead Marvels Website",
    link: "https://leadmarvels.com",
    title: "Lead Marvels Website",
    description: "Laravel  Apline.js  Tailwindscss",
  },
  {
    id: 2,
    imgSrc: "/projects/leadmarvels-newsletter.png",
    imgAlt: "Leadmarvels Newsletter Component",
    link: "https://leadmarvels.com/newsletter-signup",
    title: "Leadmarvels Newsletter Component",
    description: "Laravel  Apline.js  Tailwindscss",
  },
  {
    id: 3,
    imgSrc: "/projects/mecpahub.png",
    imgAlt: "MECPA Knowledge Hub",
    link: "https://mecpahub.org/",
    title: "MECPA Knowledge Hub",
    description: "Laravel  Apline.js  Tailwindscss",
  },
  {
    id: 4,
    imgSrc: "/projects/iacpahub.png",
    imgAlt: "IACPAHUB Resource",
    link: "https://tinyurl.com/3puh3f4f",
    title: "IACPAHUB Resource",
    description: "Laravel  Apline.js  Tailwindscss",
  },
  {
    id: 5,
    imgSrc: "/projects/smeshowcase.png",
    imgAlt: "SME Showcase",
    link: "https://smeshowcase.com/",
    title: "SME Showcase",
    description: "Laravel  Apline.js  Tailwindscss",
  },
  {
    id: 6,
    imgSrc: "/projects/alloravineyards.png",
    imgAlt: "Allora Vineyards Website",
    link: "https://www.alloravineyards.com/",
    title: "Allora Vineyards Website",
    description: "Laravel  Bootstrap",
  },
  {
    id: 7,
    imgSrc: "/projects/amelinckx.png",
    imgAlt: "Andrew Amelinckx Website",
    link: "https://andrewamelinckx.com",
    title: "Andrew Amelinckx Website",
    description: "React Tailwindscss",
  },
  {
    id: 8,
    imgSrc: "/projects/dekkerbabian.png",
    imgAlt: "Dekker Babian Website",
    link: "https://dekkerbabian.com/",
    title: "Dekker Babian Website",
    description: "React  Tailwindscss",
  },
  {
    id: 9,
    imgSrc: "/projects/hinkeinrealty.png",
    imgAlt: "Hinkein Realty Website",
    link: "https://hinkeinrealty.com/",
    title: "Hinkein Realty",
    description: "Wordpress",
  },
];
